---
- name: Install Ros2
  hosts: localhost
  gather_facts: yes
  become: yes
  roles:
    - { role: itnok.install_ros2_ubuntu }
  vars:
    install_ros2_distro: "foxy"
    install_ros2: "desktop"

- name: install python requirements
  pip:
    requirements: requirements.txt
