---
- name: Install Ros2
  hosts: localhost
  gather_facts: yes
  become: yes
  roles:
    - { role: itnok.install_ros2_ubuntu }
  vars:
    install_ros2_distro: "foxy"
    install_ros2: "desktop"

- name: install python requirements
  hosts: localhost
  become: yes
  tasks:
    - name: install command
      pip:
        requirements: requirements.txt

- name: set up git directories
  hosts: localhost
    - name: setup driving swarm infrastructure repo
      git:
        repo: git@github.com:ovgu-FINken/driving_swarm_infrastructure.git
        dest: ~/ros/driving_swarm_infrastructure
        version: master

    - name: setup dependencies workspace
      shell: |
        mkdir -o ~/ros/dependencies/src
        vcs import --input https://raw.githubusercontent.com/ovgu-FINken/driving_swarm_infrastructure/master/repo-files/turtlebot3.repos ~/ros/dependencies/src/

- name: install python requirements
  hosts: localhost
        rosdep update
        rosdep install --from-paths ~/ros/dependencies/src/ -y

    - name: build dependencies
      shell:
        cmd: colcon build
        chdir: ~/ros/dependencies
