---
- name: Install Ros2
  hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: itnok.install_ros2_ubuntu }
  vars:
    install_ros2_distro: "foxy"
    install_ros2: "desktop"

- name: Install driving_swarm_infrastructure and requirements
  hosts: all
  gather_facts: yes
  roles:
    - common