---
- name: setup machine
  hosts: localhost
  become: yes
  tasks:
    - name: install apt packages
      apt:
        name:
          - virtualbox-guest-x11
          - openssh-server

    - name: sudoers gets wheeel
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%sudo All='
        line: '%sudo ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'
    
    - name: reboot
      reboot:
  