---
- name: install chrony
  become: yes
  apt:
    name: chrony
    state: present
  tags:
    - chrony

- name: configure chrony config
  become: yes
  template: 
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
  notify: restart chrony
  tags:
    - chrony

- name: start chrony
  become: yes
  service:
    name: chrony
    state: started
    enabled: yes
  tags:
    - chrony
      
- name: install pip and other python packages
  become: yes
  apt:
    name: 
      - python3-pip
      - python3-vcstool
      - python3-skimage
      - python3-shapely
      - python3-pykdl
      - python3-termcolor
      - python3-rosdep2
    state: present
      
- name: pip requirements
  become: yes
  pip:
    name:
      - git+https://github.com/ghliu/pyReedsShepp.git
      - deprecation
      - dubins
      - bezier


- name: set up driving swarm git
  git:
    repo: https://github.com/ovgu-FINken/driving_swarm_infrastructure.git
    dest: ~/ros/driving_swarm_infrastructure
    version: master

- name: create directory for dependencies workspace
  file:
    path: ros/dependencies/src
    state: directory      

- name: configure .rosrc
  template: 
    src: rosrc.j2
    dest: ~/.rosrc

- name: add rosrc to bashrc
  lineinfile:
    path: ~/rosrc
    line: source ~/.rosrc


- name: setup dependencies workspace
  shell:
    vcs import --input https://raw.githubusercontent.com/ovgu-FINken/driving_swarm_infrastructure/master/repo-files/turtlebot3.repos ~/ros/dependencies/src/

- name: rosdep install
  shell: |
    source ~/.bashrc
    rosdep update
    rosdep install --from-paths ~/ros/dependencies/src/ -y
    
- name: build dependencies
  shell:
    cmd: |
      source ~/.bashrc
      colcon build
    chdir: ~/ros/dependencies
      
- name: add dependencies to rosrc
  lineinfile:
    path: ~/.rosrc
    line: source ~/ros/depenencies/install/setup.bash
      
- name: build driving swarm
  shell:
    cmd: |
      source ~/.bashrc
      colcon build
    chdir: ~/ros/driving_swarm_infrastructure

- name: add driving_swarm_infrastructure to rosrc
  lineinfile:
    path: ~/.rosrc
    line: source ~/ros/driving_swarm_infrastructure/install/local_setup.bash
