---
- name: install chrony
  become: yes
  apt:
    name: chrony
    state: present
  tags:
    - chrony

- name: configure chrony config
  become: yes
  template: 
        src: chrony.conf.j2
        dest: /etc/chrony/chrony.conf
        owner: root
        group: root
        mode: 0644
  notify: restart chrony
  tags:
    - chrony

- name: start chrony
  become: yes
  service:
    name: chrony
    state: started
    enabled: yes
  tags:
    - chrony
      
- name: pip requirements
  become: yes
  pip:
    name:
      - vcs-tool
      - git+https://github.com/ghliu/pyReedsShepp.git
      - graph-tool
      - deprecation
      - skimage
      - shapely
      - dubins
      - bezier
      - pykdl
      - termcolor


- name: set up driving swarm git
  git:
    repo: git@github.com:ovgu-FINken/driving_swarm_infrastructure.git
    dest: ~/ros/driving_swarm_infrastructure
    version: master

- name: setup dependencies workspace
  shell: |
    mkdir -o ~/ros/dependencies/src
    vcs import --input https://raw.githubusercontent.com/ovgu-FINken/driving_swarm_infrastructure/master/repo-files/turtlebot3.repos ~/ros/dependencies/src/

- name: rosdep install
  shell: |
    rosdep update
    rosdep install --from-paths ~/ros/dependencies/src/ -y
    
- name: configure .rosrc
  template: 
    src: rosrc.j2
    dest: ~/.rosrc

- name: add rosrc to bashrc
  lineinfile:
    path: ~/rosrc
    line: source ~/.rosrc

- name: build dependencies
  shell:
    cmd: colcon build
    chdir: ~/ros/dependencies

- name: build driving swarm
  shell:
    cmd: colcon build
    chdir: ~/ros/driving_swarm_infrastructure
